POST  http://localhost:3000/employees
Content-Type: application/json

{
    "ID_Employee": "4260",
    "Type_Pay": "Semanal",
    "Area": "1198 Nitco Vtc",
    "Ubication": "NITCO",
    "Employee": "Lucas Jesus Alejandro",
    "Position": "Almacenista",
    "Fecha_Ingreso": "12/Noviembre/2021",
    "Estado": "Activo",
    "User_Type": ""
}

###
GET http://localhost:3000/employee

###
POST http://localhost:3000/salarys
Content-Type: application/json

{
    "ID_Employee": "4301",
    "Cost_Clasification": "Semanal",
    "Daily_Salary": 173,
    "Antiquity": 0.13,
    "Worked_Days": 30
}

###
GET http://localhost:3000/salarys/EmployeeSalary/4301
# Content-Type: application/json

# {
#     "_id": "62b5d333ac90b711379886f8"
# }

###
GET http://localhost:3000/salarys
Content-Type: application/json

{
    "_id": "62b9c9368c0a5a690e7443b0"
}   

###
GET http://localhost:3000/employees/employee

###
GET http://localhost:3000/area-produccion

###
POST http://localhost:3000/area-produccion
Content-Type: application/json

{
    "Area_Produccion": "2500 Rpk Ii"
}

###
GET http://localhost:3000/employee/employees-position/Almacenista

###
GET http://localhost:3000/salarys/

### 
PUT http://localhost:3000/epp/edit-accesoriesData/62d0453c61585782c8c2bf12
Content-Type: application/json

{
    "Casco_Hombre": 37,
    "Casco_Mujer": 55.96,
    "Suspension": 37,
    "Barbiquejo": 10,
    "Mangas_Anticorte": 81.64,
    "Mangas_Kevlar": 67,
    "Guantes_Kevlar": 111,
    "Guantes_Nitrilo": 60
}

###
GET http://localhost:3000/epp/
###
PUT http://localhost:3000/epp/edit-accesoriesData/62d0453c61585782c8c2bf12
Content-Type: application/json

{
    "Casco_Hombre": 37
}
###
PUT http://localhost:3000/recruitment/edit-recruitmenInfo/62d0452661585782c8c2bf10
Content-Type: application/json

{
  "Broche": 2
}

###
GET http://localhost:3000/uniforms

###
GET http://localhost:3000/medical-test/

###
GET http://localhost:3000/prueba/prueba-usertype

###
GET http://localhost:3000/imss/imms-info

###
GET http://localhost:3000/users/get-users

### 
POST http://localhost:3000/position-almacen/create-data
Content-Type: application/json

{
    "Almacen": "NITCO",
    "Posiciones": [
        {"Manager":true},
        {"Jefe de Almacen":false},
        {"Assistant": true},
        {"ControlAnalyst": true},
        {"Supervisor": true},
        {"Leader": true},
        {"4W FklDriver": true},
        {"Reach Driver": true},
        {"Order Picker": true},
        {"QC Insp": true},
        {"Data Entry Clerck": true},
        {"Operator": true}
    ]
}

###
PUT http://localhost:3000/employee/edit-status/4309
Content-Type: application/json

{
    "fecha": "2022-05-07T05:00:00.000+00:00"
}

###
GET http://localhost:3000/position-almacen/almacen-data

###
POST http://localhost:3000/headcount/create-inflacion
Content-Type:  application/json

{
    "Inflacion":0,
    "Bonus_Puntualidad":0.1,
    "Asistencia":0.1,
    "Despensa":0.05,
    "Fondo_Ahorro":0.13,
    "Comida":68.25,
    "Servicio_Medico":6660,
    "Bonus_Productividad":22,
    "Indemnizacion":7.5,
    "Bonus_Vacacional":0.25,
    "Impues_Sobre_Nomina":0.02,
    "Seguro_Medico":1125,
    "Seguro_Vida":1125
}

###
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
    "Name": "Francisco González Lara",
    "Nomina":3312,
    "Contrasena": "Contrasena123",
    "Privilegios": 7
}

###
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
    "Name": "Francisco González Lara",
    "Nomina":3312,
    "Contrasena": "Contrasena123",
    "Privilegios": 1
}

###
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
    "Name": "Luis Gómez Solis",
    "Nomina":1233,
    "Contrasena": "Contrasena123",
    "Privilegios": 12
}

###
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
    "Name": "Gabriel Davila",
    "Nomina":4534,
    "Contrasena": "Contrasena123",
    "Privilegios": 13
}

###
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
    "Name": "Karla Luevano",
    "Nomina": 4588,
    "Contrasena": "Contrasena123",
    "Privilegios": 3,
    "Almacen":"RPK-2"
}
###
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
    "Name": "Orlando Hernandez",
    "Nomina": 1313,
    "Contrasena": "Contrasena123",
    "Privilegios": 4
}

###
POST http://localhost:3000/users/valid-user
Content-Type: application/json

{
    "Nomina":12345,
    "Contrasena": "Contrasena123"
}

###
GET http://localhost:3000/imssData/imss-data

### redes ------------------------------------------------------------------
POST http://localhost:8080/proyecto-redes/create-user
Content-Type: application/json

{
    "Correo":"prueba2@gmail.com",
    "Alias":"ISC2",
    "Contrasena": "Contrasena123"
}

###
GET http://localhost:8080/proyecto-redes/get-user/ISC

###
POST http://localhost:8080/proyecto-redes/valid-user
Content-Type: application/json

{
    "Correo":"prueba2@gmail.com",
    "Contrasena":"Contrasena123"
}

### tareas
POST http://localhost:8080/proyecto-redes/create-task
Content-Type: application/json

{
    "Nombre":"Tarea1",
    "Descripcion":"Se realiza una prueba de creacion de tarea",
    "Fecha":"2022-11-21",
    "Fecha_Realizada":"2022-11-21",
    "Importancia":"Importante",
    "Estatus": 0,
    "User":"ISC2"
}

###
GET http://localhost:8080/proyecto-redes/get-pendingTasks/ISC
###
GET http://localhost:8080/proyecto-redes/get-completedTasks/ISC

###
POST http://localhost:8080/proyecto-redes/edit-task
Content-Type: application/json 

{
    "id":"638811a39b9da123c3783819"
}

### frases
POST http://localhost:8080/proyecto-redes/save-quote
Content-Type: application/json

{
    "Frase": "Esto es una frase celebre xd",
    "Autor": "Francisco González Lara",
    "Fecha": "2022-11-21",
    "User": "ISC",
    "Motivo": "Esto es un motivo por el cual me gusto la frase"
}

###
GET http://localhost:8080/proyecto-redes/get-quotes/ISC

###
DELETE http://localhost:8080/proyecto-redes/delete-quote/638941836ea93d75a92467e3

### Ubicacion
POST http://localhost:8080/proyecto-redes/create-ubicacion
Content-Type: application/json

{
    "cityName": "Colombia",
    "countryCode": "CO",
    "User": "ISC2"
}

###
GET http://localhost:8080/proyecto-redes/get-ubicacion/ISC

###
POST http://localhost:8080/proyecto-redes/edit-ubicacion
Content-Type: application/json

{
    "_id": "638942d0ef64738c295711cc",
    "cityName": "Colombia",
    "countryCode": "co",
    "User": "ISC"
}

### Prueba
GET http://localhost:8080/proyecto-redes/prueba

###
GET http://localhost:8080/proyecto-redes/create-db